name: Kustomize Validation
author: CCC
description: A Kustomize(ish) validator

inputs:
  base-directory:
    description: 'Base directory of operations'
    required: false
    default: "."
  depth:
    description: 'Depth'
    required: false
    default: "4"
  debug:
    description: 'Debug logging'
    required: false
    default: "0"

runs:
  using: 'docker'
  image: 'docker://ghcr.io/clingclangclick/pre-commit-docker-kustomize/pre-commit-docker-kustomize:0.2.0'
  args:
    - ${{ inputs.base-directory }}
    - ${{ inputs.depth }}
    - ${{ inputs.debug }}