#!/usr/bin/env sh

find "$BASEDIR"/"$1" -maxdepth "${2:-4}" -mindepth "${2:-4}" -type d | \
while read -r d
do
    echo "Validating path: ${d#"$BASE_DIR"/*}"
    (cd "$d" && kustomize build >/dev/null)
done
